### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by huankong233** [SoraRoseous/ChatSydney-react#1]
~~~
C:\Users\huan_kong\Desktop\code\ChatSydney-react\main.py:148: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Go to http://localhost:65432 to start chatting!
Traceback (most recent call last):
  File "C:\Users\huan_kong\Desktop\code\ChatSydney-react\main.py", line 28, in sydney_process_message
    async for _, response in chatbot.ask_stream(prompt=user_message, conversation_style="creative", raw=True,
  File "C:\Users\huan_kong\AppData\Roaming\Python\Python310\site-packages\SydneyGPT\SydneyGPT.py", line 30, in ask_stream
    async for key, value in super().ask_stream(*args, **kwargs):
  File "C:\Users\huan_kong\AppData\Roaming\Python\Python310\site-packages\EdgeGPT\EdgeGPT.py", line 185, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "C:\Users\huan_kong\AppData\Roaming\Python\Python310\site-packages\SydneyGPT\SydneyGPT.py", line 55, in ask_stream
    async for key, value in super().ask_stream(*args, **kwargs):
  File "C:\Users\huan_kong\AppData\Roaming\Python\Python310\site-packages\EdgeGPT\chathub.py", line 102, in ask_stream
    async with connect(
  File "C:\Users\huan_kong\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\client.py", line 633, in __aenter__
    return await self
  File "C:\Users\huan_kong\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\client.py", line 650, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "C:\Program Files\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\huan_kong\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\client.py", line 659, in __await_impl__
    await protocol.handshake(
  File "C:\Users\huan_kong\AppData\Roaming\Python\Python310\site-packages\websockets\legacy\client.py", line 328, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200
~~~

**Comment by SoraRoseous** [comment]
edgeGPT0.11.8里面把创建ws连接的代理移除了，现在想正常使用的话得开全局代理，或者等修复吧😂

**Comment by huankong233** [comment]
好的，谢谢，打扰了
