### ISSUE TITLE
我在一个新电脑上部署出现了如下报错……

### ISSUE THREAD

**Issue by lioensky** [SoraRoseous/ChatSydney-react#18]
Traceback (most recent call last):
  File "C:\MyFiles\App\ChatSydney-react-react\EdgeGPT\conversation.py", line 121, in create
    self.struct = response.json()
                  ^^^^^^^^^^^^^^^
  File "C:\Users\xueji\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\httpx\_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\MyFiles\App\ChatSydney-react-react\main.py", line 33, in sydney_process_message
    chatbot = await Chatbot.create(cookies=cookies, proxy=args.proxy, imgid=imgid)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MyFiles\App\ChatSydney-react-react\EdgeGPT\EdgeGPT.py", line 43, in create
    await Conversation.create(self.proxy, cookies=cookies, imgid=imgid),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MyFiles\App\ChatSydney-react-react\EdgeGPT\conversation.py", line 125, in create
    raise Exception(
Exception: Authentication failed. You have not been accepted into the beta.

**Comment by SoraRoseous** [comment]
检查一下账号是否能在官网正常使用，如果可以的话就更新一下cookie再试试
